module.exports = [
  { id: 0, from: "Corey", date: "April 10", name: "Code Along", amount: 10 },
  { id: 1, from: "Corey", date: "April 7", name: "AirPods", amount: 200 },
  { id: 2, from: "Corey", date: "April 9", name: "Apple", amount: -53 },
  { id: 3, from: "Corey", date: "April 28", name: "Taxes", amount: 123 },
  { id: 4, from: "Gigi", date: "April 19", name: "One Thing", amount: 40 },
  { id: 5, from: "Gigi", date: "April 1", name: "Dog Food", amount: 20 },
  { id: 6, from: "Gigi", date: "April 3", name: "Car Wash", amount: 13 },
  { id: 7, from: "Gigi", date: "April 8", name: "Electric Bill", amount: 231 },
  { id: 8, from: "Tim", date: "May 20", name: "Groceries", amount: 30 },
  { id: 9, from: "Tim", date: "May 20", name: "New Light Bulbs", amount: 10 },
  { id: 10, from: "Tim", date: "May 17", name: "Hair Cut", amount: 25 },
  { id: 11, from: "Tim", date: "May 17", name: "Venmo", amount: 109 },
  { id: 12, from: "Mashu", date: "May 19", name: "Fruit", amount: -10 },
  { id: 13, from: "Mashu", date: "May 19", name: "BBQ", amount: 50 },
  { id: 14, from: "Mashu", date: "May 27", name: "Taxi", amount: 38 },
  { id: 15, from: "Mashu", date: "May 27", name: "Github", amount: 7 },
];
